spring:
  jackson:
    #  格式化返回时间 yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookstore?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 9090
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

files:
  upload:
    path: C:\Users\15382\Desktop\毕设\code product\bookstore\files\

alipay:
  appId: 2021000122608441
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCjHCKUPsuKdFFCXKFrUtPDEpFKlijxnQ7WGFfI18aAx6KOO/kDH8pEab15YdybpIIdiSkWWUY8NlzpLt5IhG2Usq88Q5Kf9vrXBo5Zaxp6yVFOmFQP6BfhTnc1zDgt1ZG1sKf7TXZTb17G1Q9nHEm1T0XOlfdudF32Edk6UAh9dDQmKLjobZJ+zQPl35rVBuBaiukHRwC8k8Dv8OWnbrAp8JmzWu+SpIG2hk/spASwIVUAU1wZ1mZvydp3bcVWUZbUEkXccdcbf9UrZNdvk6mUUJmk2aIhDUxf86NQ1H96rZcDXNNKbknq1u6VECC5MqFbr3skix2Td7Py0gguKtgRAgMBAAECggEAKya0VzfNrVFcdgv/gF8nOsJcwbi8GD+Ov0EtaCr9jvBBpxNiq1rrrfGzeLtVG7AH5Dx3LDxuAlv3dJE7qT+vpdkn1u+hiMRUVDKd0jYtiTJdWkeeZZ7nQmn5y7e9XRLVO5YCus8hcK1UC5IuQv8O2PKh6ydtkEEk4oaSS4UE2ftJLNlijokWHfpbbPbpwoJqggxiEPEU58sffMZ4avwqb7161SUUbX1KAxllBwAGmohKv3fnvnFXwzsuyMQX9uf4NtXV7FJ/W6nvVCRww8vuStUuyPZJ1fzPYJIPZFD7JZUX3XXWmaYiRBsoFEzFJYRXJ2wgfumRBj4MCw1VtY8uKQKBgQDmwqbxvT4UCRgU7UzG/gDXPtyL78BAei6HqmOkGYbYCfmxcGoCmpnwNfk2ZgsWWIsINfsEU0Z5wgJwn/kjF4s8qCbWcIWzHgANu8ocPqetXQqhtoLanDBmsVFIweL9dnLrPfCVkVXgZ/U+Kcg/Lx9l1qfTjXeiiMdZBsyOFrb6PwKBgQC080DR1JPq6N5nMyCm351GnQL3hFRQrh9OW6QndRdlm1+sTin8I6HrarUVCAOZ4GsT8p10tdyGDUREqdj3uKXw0wg3Xs3+obqPRI1mSZHMN7HKPsOlhno+wV1mis25jhqFOccEWlI0YeAAzyPzV45V1bfGnIJAIZa37UVXFbJ5rwKBgQCCuvPpL9TjdON3t5gvg+bmCm7XuFOqM434vccFSJDkA4K5y33DS+K5+1ncP6M4XaEmXa5/nM3oXMkVFQwHnWb8TibyhXy5JN3S6fhuV/CWfodvZf5r6uBgzUPHfFAkV95y9vw9P8DvCPYe6XzQjtmy0BD0AMkuA18sSHXKaYPv8QKBgHeM23+Ghi/GqOHf+qulw8BajhJAIICpec+IZl0XVFzyGXS6s6x9UkY6WudJQy/QAI7OVU89tDPw4fDHkqygFyqUErKadVjNO3faX917r9MP3Ov1KcfboDqEAJR2ElOM2mK4+I8cqYEoRRnjwSnN6CE3sVKMJtX+Gxjrr0tI74DLAoGBAMY8/wDZZS811emKoVyosXmByZPB1dn6jUNFSf50ZbnQ3JrqRd6IF3zCESHZe61i5lAsjQQMjiDBXgZs/x1f3G+L3ukA8P1j+Wx1m2jDK82YUlt+zvohqsHmNnk7KvwjfxfKscedcOeUNJC0htpgj9+jERFymoPdikPy2qebJR6V
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAklzvwS1p8Mp1rZoZcxFV2HNku/bbmhv5AAurdXkgZcorfOFTZTYqbGQFd1po1BNTfwAvDfCHX0vhcWQS1azzp5v1SOTuYzNZZDAfSvo0cV8AnixbZ5SXQq3go0w8WlgkOSKivoesTwBk9fhlzskJq/wJBY3ovSYyS/rc9aNY8g4D7hFCebOKo6HZ6bXEtjMaxj6ow8SlQ43cWj28ZNqocPnHbkDiiKdmg3bGBenb0LHgoMLKegCatTHE0xQeAm1X82egpgctAQehQ6ug29JUYs00shWBeXoVaLkMCw/O6z4ocTeWbug5LRLmkulP5gM3ou1hswG8QOBQq8W+VwEGFQIDAQAB
#  notifyUrl: http://muaqx9.natappfree.cc/alipay/notify



